name: Hola mundo

on:
  push:
    branches:
      - main

jobs:

  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Hola mundo
      run: echo 'Hola mundo'

  write-file:
    runs-on: ubuntu-latest
    needs: [hello-world]
    steps:
    - name: Write to file
      run: echo 'Hello, world!' > hello.txt
    - name: Display file
      run: cat hello.txt

  list-files:
    runs-on: ubuntu-latest
    needs: [write-file]
    steps:
    - uses: actions/checkout@v2
    - name: List files
      run: ls -a