name: Local Action CI
on:
  push:
    branches:
      - main
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3
      - name: Run local action
        uses: ./.github/actions/local-action-1