name: .NET Core CI
'on':
  push:
    branches:
      - main
env:
  PROJECT_PATH: src/section_1
  TEST_PROJECT_PATH: src/section_1_test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: 'dotnet restore ${{ env.PROJECT_PATH }}/section_1.csproj'
      - name: Build the solution
        run: >-
          dotnet build ${{ env.PROJECT_PATH }}/section_1.csproj --configuration
          Release --no-restore
      - name: Run unit tests
        run: >-
          dotnet test ${{ env.TEST_PROJECT_PATH }}/section_1_test.csproj
          --verbosity minimal
