name: Script CI
'on':
  push:
    branches:
      - main
jobs:
  script-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3
      - name: Verify script presence
        run: ls -la scripts/
      - name: Run script
        run: |
          chmod +x scripts/script.sh
          echo "Running script.sh..."
          ./scripts/script.sh
